---

- hosts: localhost
  connection: local
  gather_facts: false

  # $ curl -w "\n" 'https://discovery.etcd.io/new?size=3'
  # https://discovery.etcd.io/6a28e078895c5ec737174db2419bb2f3

  vars:
    coreos:
      etcd_token: ""
      do_token: ""
      droplets:
        - { name: kubernetes-master,     size: "512mb",   group: "kube-master" }
        - { name: kubernetes-minion-1,   size: "512mb",   group: "kube-minions" }
        - { name: kubernetes-minion-2,   size: "512mb",   group: "kube-minions" }

  roles:
    - { role: coreos }
